version: "3.7"

services:
  bot:
    build: .
    command: /app/startup.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
